# Generated by Django 5.2.3 on 2025-06-20 16:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('opportunity_id', models.CharField(max_length=50, unique=True)),
                ('opportunity_name', models.CharField(max_length=200)),
                ('status', models.CharField(default='open', max_length=20)),
                ('lead_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opportunity_source', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('pipeline_stage', models.CharField(max_length=100)),
                ('pipeline_name', models.CharField(max_length=100)),
                ('quote_link', models.URLField(blank=True, null=True)),
                ('user_name', models.CharField(max_length=100)),
                ('handler', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('employee_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price/rate for the employee', max_digits=10)),
                ('user_type', models.CharField(choices=[('assigner', 'Assigner'), ('worker', 'Worker')], default='worker', help_text='Type of user: assigner or worker', max_length=10)),
                ('date_created', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-date_created'],
            },
        ),
    ]
