# Generated by Django 5.2.3 on 2025-06-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='user_type',
            field=models.CharField(choices=[('handler', 'Handler'), ('Worker Assigned', 'Worker Assigned')], default='Worker Assigned', help_text='Type of user: assigner or worker'),
        ),
    ]
