# Generated by Django 5.2.3 on 2025-06-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_lead_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='handler',
        ),
    ]
