# Generated by Django 4.2 on 2025-06-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_lead_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='opportunity_id',
            field=models.CharField(max_length=50),
        ),
    ]
